# Generated by Django 5.2 on 2025-04-06 08:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID плейлиста')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='playlists/covers/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Плейлист',
                'verbose_name_plural': 'Плейлисты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID записи')),
                ('article_id', models.PositiveIntegerField(verbose_name='ID статьи')),
                ('user_id', models.PositiveIntegerField(verbose_name='ID пользователя')),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='user.playlist', verbose_name='Плейлист')),
            ],
            options={
                'verbose_name': 'Статья в плейлисте',
                'verbose_name_plural': 'Статьи в плейлистах',
                'ordering': ['playlist_id', 'article_id'],
            },
        ),
    ]
