# Generated by Django 5.2 on 2025-04-06 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.CharField(choices=[('atom', 'Атом'), ('dna', 'ДНК'), ('rocket', 'Ракета'), ('flask', 'Колба'), ('microscope', 'Микроскоп')], default='atom', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID записи')),
                ('article_id', models.PositiveIntegerField(verbose_name='ID статьи')),
                ('user_id', models.PositiveIntegerField(verbose_name='ID пользователя')),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='user.playlist', verbose_name='Плейлист')),
            ],
            options={
                'verbose_name': 'Статья в плейлисте',
                'verbose_name_plural': 'Статьи в плейлистах',
                'ordering': ['playlist_id', 'article_id'],
            },
        ),
    ]
